app = 'fly-metrics-proxy'
primary_region = 'dfw'

[build]

[env]
  METRICS_TARGETS = """
[
  {
    "endpoint": "https://example.com/1/metrics",
    "labels": {"app_name": "example_1", "environment": "production"}
  },
  {
    "endpoint": "https://example.com/2/metrics",
    "labels": {"app_name": "example_2", "environment": "staging", "service": "frontend"}
  }
]
"""

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[metrics]
  port = 8080
  path = '/metrics'
  https = false
