app = 'fly-metrics-proxy'
primary_region = 'dfw'

[build]

[env]
  METRICS_TARGETS = """
[
  {
    "endpoint": "https://example.com/1/metrics",
    "queue_name": "metrics_1"
  },
  {
    "endpoint": "https://example.com/2/metrics",
    "queue_name": "metrics_2"
  }
]
"""

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[metrics]
  port = 8080
  path = '/metrics'
  https = false
